App:
  Name: "golang-clean-architecture"
  Version: "v0.0.1"
  Scheme: "http"
  Host: "localhost:3002"
  Environment: local #local,development,staging,production

Server:
  Port: "9090"
  Debug: true
  TimeZone: "America/Sao_Paulo"

Database:
  Host: 127.0.0.1
  Port: 3306
  Name: produtos
  User: root
  Password: admin

Authentication:
  Key: DoWithLogic!@#
